name: Sync files to website repo

on:
  workflow_dispatch:
  push:
    paths:
      - '*.csv'
      - 'visualization.js'
  schedule:
    - cron: '0 * * * *'  # Run every hour

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout see repo
      uses: actions/checkout@v4
      with:
        path: see

    - name: Checkout website repo
      uses: actions/checkout@v4
      with:
        repository: bilals12/website
        token: ${{ secrets.WEBSITE_REPO_TOKEN }}
        path: website

    - name: Sync files
      run: |
        set -x  # Enable verbose output
        mkdir -p website/static/js
        cp see/*.csv website/static/ || echo "No CSV files found"
        cp see/visualization.js website/static/js/ || echo "visualization.js not found"
        cd website
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git status
        git diff --staged --quiet || (git commit -m "Sync CSV and JS files from see repo" && git push) || echo "No changes to commit"
      env:
        GITHUB_TOKEN: ${{ secrets.WEBSITE_REPO_TOKEN }}
        