name: Sync files to website repo

on:
  workflow_dispatch:
  push:
    paths:
      - '*.csv'
  schedule:
    - cron: '0 0 * * *'  # Run once a day at midnight

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout see repo
      uses: actions/checkout@v4
      with:
        path: see

    - name: Checkout website repo
      uses: actions/checkout@v4
      with:
        repository: bilals12/website
        token: ${{ secrets.WEBSITE_REPO_TOKEN }}
        path: website

    - name: Sync files
      run: |
        set -x  # Enable verbose output
        cp see/*.csv website/static/viz || echo "No CSV files found"
        cd website
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Sync CSV and JS files from see repo" || echo "No changes to commit"
        git push || echo "Push failed"
      env:
        GITHUB_TOKEN: ${{ secrets.WEBSITE_REPO_TOKEN }}
